//
// Created by qnbhd on 05.12.2019.
//

#pragma once

#define __APPLICATION_SIZE_WIDTH  800
#define __APPLICATION_SIZE_HEIGHT 600

#define __APPLICATION_DEFAULT_MISC_FOLDER "misc/"

#define __APPLICATION_DEFAULT_TITLE "QNGraph"
#define __APPLICATION_SETTINGS_EXTENSION

#define __APPLICATION_CPP_COMPILER_VERSION 17

#define __SETTINGS_MAIN_FONT_PATH "misc/fonts/OpenSans-Regular.ttf"

#define __SETTINGS_BACKGROUND_COLOR                   0xFFFFFF
#define __SETTINGS_CURRENT_THEME_MAIN_COLOR           #311B92
#define __SETTINGS_CURRENT_THEME_MAIN_COLOR_D         0x31, 0x1B, 0x92
#define __SETTINGS_CURRENT_THEME_LIGHT_COLOR          #6746C3
#define __SETTINGS_CURRENT_THEME_LIGHT_COLOR_D        0x67, 0x46, 0xC3
#define __SETTINGS_CURRENT_THEME_DARK_COLOR           #000063
#define __SETTINGS_CURRENT_THEME_DARK_COLOR_D         0x00, 0x00, 0x63
#define __SETTINGS_CURRENT_THEME_ACCENT_COLOR         #D81B60
#define __SETTINGS_CURRENT_THEME_ACCENT_COLOR_D       0xD8, 0x1B, 0x60
#define __SETTINGS_CURRENT_THEME_ACCENT_LIGHT_COLOR   #FF5C8D
#define __SETTINGS_CURRENT_THEME_ACCENT_LIGHT_COLOR_D 0xFF, 0x5C, 0x8D
#define __SETTINGS_CURRENT_THEME_ACCENT_DARK_COLOR    #A00037
#define __SETTINGS_CURRENT_THEME_ACCENT_DARK_COLOR_D  0xA0, 0x00, 0x37

#define __AUTHOR QNBHD
#define __APP_DATE "05.12.2019"







